"""Tests for the legacy xlsx importer.

Uses synthetic xlsx fixtures generated by openpyxl — no real data files
in the repo. Tests cover the parser, normalizer, validator, classifier,
and dry-run report shape.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_PLATFORM_ROOT = Path(__file__).resolve().parents[1]
if str(_PLATFORM_ROOT) not in sys.path:
    sys.path.insert(0, str(_PLATFORM_ROOT))

from scripts.import_legacy_xlsx import (  # noqa: E402
    Outcome,
    classify_row,
    load_column_map,
    normalize_row,
    parse_sheet,
    validate_row,
    build_report,
)
from modules.projects.codes import next_job_code  # noqa: E402


# ---------------------------------------------------------------------------
# Fixtures — synthetic xlsx files
# ---------------------------------------------------------------------------
@pytest.fixture()
def legacy_xlsx(tmp_path):
    """Create a synthetic legacy xlsx with a Projects sheet."""
    import openpyxl

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Projects"

    # Header at row 3 (matching the legacy_map.yaml header_row: 3)
    # Rows 1-2 are blank / title rows
    ws.cell(row=1, column=1, value="Project Tracker 2026")
    ws.cell(row=2, column=1, value="")

    headers = [
        "Folder", "Project No", "Project Description / Address",
        "Priority", "Project Status", "Action By", "Next Action",
        "Date Opened", "Target Close", "% Complete",
        "Process No.", "Contact", "Company / Client",
        "Scope of Work", "Contract Value ($)", "Amount Paid ($)",
        "Outstanding Balance ($)", "COGS", "Profit",
        "Service Type", "Notes",
    ]
    for col_idx, header in enumerate(headers, start=1):
        ws.cell(row=3, column=col_idx, value=header)

    # Data rows (row 4+) — synthetic data only
    test_data = [
        # Row 1: valid active project
        {
            "Folder": "260101 - Test Alpha",
            "Project No": 260101,
            "Project Description / Address": "Alpha Engineering Study",
            "Priority": "High",
            "Project Status": "Active",
            "Action By": "6DE",
            "Next Action": "Submit report",
            "Date Opened": "2026-01-15",
            "Target Close": "2026-06-30",
            "% Complete": 0.45,
            "Contact": "Jane Doe",
            "Company / Client": "Acme Corp",
            "Scope of Work": "Structural assessment",
            "Contract Value ($)": 15000,
            "Amount Paid ($)": 7500,
            "Outstanding Balance ($)": 7500,
            "Notes": "Phase 1 complete",
        },
        # Row 2: drafting status with emoji priority
        {
            "Folder": "260201 - Test Beta",
            "Project No": 260201,
            "Project Description / Address": "Beta Renovation",
            "Priority": "🔴 Medium",
            "Project Status": "Drafting",
            "Action By": "Client",
            "Date Opened": "2026-02-01",
            "% Complete": "75%",
            "Company / Client": "Beta LLC",
            "Scope of Work": "Renovation plans",
        },
        # Row 3: AHJ/Permitting with percentage as decimal
        {
            "Project No": 260301,
            "Project Description / Address": "Gamma Permit Package",
            "Project Status": "AHJ/Permitting",
            "% Complete": 0.9,
            "Company / Client": "Gamma Inc",
        },
        # Row 4: invalid status (should fail validation)
        {
            "Project No": 260401,
            "Project Description / Address": "Delta Invalid",
            "Project Status": "🚀 Launched",
        },
        # Row 5: no job number or name (should fail)
        {
            "Priority": "Low",
        },
        # Row 6: completed project
        {
            "Project No": 260501,
            "Project Description / Address": "Epsilon Complete",
            "Project Status": "Completed",
            "% Complete": 1.0,
        },
    ]

    for row_idx, data in enumerate(test_data, start=4):
        for col_idx, header in enumerate(headers, start=1):
            val = data.get(header)
            if val is not None:
                ws.cell(row=row_idx, column=col_idx, value=val)

    file_path = tmp_path / "test_tracker.xlsx"
    wb.save(file_path)
    wb.close()
    return file_path


@pytest.fixture()
def col_map():
    """Load the default column map."""
    return load_column_map()


# ---------------------------------------------------------------------------
# Parser tests
# ---------------------------------------------------------------------------
class TestParseSheet:
    def test_parses_correct_row_count(self, legacy_xlsx, col_map):
        rows = parse_sheet(legacy_xlsx, sheet_name="Projects", column_map=col_map)
        assert len(rows) == 6

    def test_maps_columns_to_platform_fields(self, legacy_xlsx, col_map):
        rows = parse_sheet(legacy_xlsx, sheet_name="Projects", column_map=col_map)
        first = rows[0]
        assert "job_number" in first
        assert "name" in first
        assert "status" in first
        assert first["job_number"] == 260101 or str(first["job_number"]) == "260101"

    def test_unmapped_columns_excluded(self, legacy_xlsx, col_map):
        rows = parse_sheet(legacy_xlsx, sheet_name="Projects", column_map=col_map)
        first = rows[0]
        assert "Process No." not in first
        assert "Service Type" not in first

    def test_empty_sheet_returns_empty(self, tmp_path, col_map):
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Projects"
        file_path = tmp_path / "empty.xlsx"
        wb.save(file_path)
        wb.close()
        rows = parse_sheet(file_path, sheet_name="Projects", column_map=col_map)
        assert rows == []


# ---------------------------------------------------------------------------
# Normalizer tests
# ---------------------------------------------------------------------------
class TestNormalizeRow:
    def test_status_mapped(self, col_map):
        raw = {"status": "AHJ/Permitting", "job_number": "260301", "name": "Test"}
        norm = normalize_row(raw, col_map)
        assert norm["status"] == "ahj_permitting"

    def test_priority_mapped(self, col_map):
        raw = {"priority": "Medium", "job_number": "260001", "name": "Test"}
        norm = normalize_row(raw, col_map)
        assert norm["priority"] == "normal"

    def test_priority_emoji_stripped(self, col_map):
        raw = {"priority": "🔴 High", "job_number": "260001", "name": "Test"}
        norm = normalize_row(raw, col_map)
        assert norm["priority"] == "high"

    def test_percent_decimal_converted(self, col_map):
        raw = {"percent_complete": 0.45, "job_number": "260001", "name": "Test"}
        norm = normalize_row(raw, col_map)
        assert norm["percent_complete"] == 45

    def test_percent_string_converted(self, col_map):
        raw = {"percent_complete": "75%", "job_number": "260001", "name": "Test"}
        norm = normalize_row(raw, col_map)
        assert norm["percent_complete"] == 75

    def test_job_number_padded(self, col_map):
        raw = {"job_number": "1234", "name": "Test"}
        norm = normalize_row(raw, col_map)
        assert norm["job_number"] == "001234"

    def test_default_status_active(self, col_map):
        raw = {"job_number": "260001", "name": "Test"}
        norm = normalize_row(raw, col_map)
        assert norm["status"] == "active"


# ---------------------------------------------------------------------------
# Validator tests
# ---------------------------------------------------------------------------
class TestValidateRow:
    def test_valid_row_no_errors(self):
        row = {"job_number": "260101", "name": "Test", "status": "active"}
        errors = validate_row(row, 0)
        assert errors == []

    def test_invalid_status_fails(self):
        row = {"job_number": "260101", "name": "Test", "status": "launched"}
        errors = validate_row(row, 0)
        assert any("status" in e.lower() for e in errors)

    def test_invalid_priority_fails(self):
        row = {"job_number": "260101", "name": "Test", "status": "active",
               "priority": "extreme"}
        errors = validate_row(row, 0)
        assert any("priority" in e.lower() for e in errors)

    def test_no_job_or_name_fails(self):
        row = {"status": "active"}
        errors = validate_row(row, 0)
        assert any("neither" in e.lower() for e in errors)


# ---------------------------------------------------------------------------
# Classifier tests
# ---------------------------------------------------------------------------
class TestClassifyRow:
    def test_new_row_creates(self):
        row = {"job_number": "260101", "name": "Test", "status": "active"}
        outcome, errors = classify_row(row, 0, existing_jobs=set())
        assert outcome == Outcome.CREATE
        assert errors == []

    def test_existing_job_updates(self):
        row = {"job_number": "260101", "name": "Test", "status": "active"}
        outcome, errors = classify_row(row, 0, existing_jobs={"260101"})
        assert outcome == Outcome.UPDATE
        assert errors == []

    def test_invalid_row_fails(self):
        row = {"job_number": "260101", "name": "Test", "status": "bogus"}
        outcome, errors = classify_row(row, 0, existing_jobs=set())
        assert outcome == Outcome.FAIL
        assert len(errors) > 0


# ---------------------------------------------------------------------------
# Report shape tests
# ---------------------------------------------------------------------------
class TestReportShape:
    def test_report_has_required_keys(self):
        results = [
            {"row": 1, "job_number": "260101", "name": "A", "outcome": Outcome.CREATE, "errors": []},
            {"row": 2, "job_number": "260201", "name": "B", "outcome": Outcome.UPDATE, "errors": []},
            {"row": 3, "job_number": "260301", "name": "C", "outcome": Outcome.FAIL,
             "errors": ["Invalid status"]},
        ]
        report = build_report(results, "test.xlsx", "Projects", commit=False)

        assert "summary" in report
        assert "rows" in report
        s = report["summary"]
        assert s["file"] == "test.xlsx"
        assert s["sheet"] == "Projects"
        assert s["mode"] == "DRY-RUN"
        assert s["total_rows"] == 3
        assert s["create"] == 1
        assert s["update"] == 1
        assert s["fail"] == 1

    def test_commit_mode_in_report(self):
        report = build_report([], "test.xlsx", None, commit=True)
        assert report["summary"]["mode"] == "COMMIT"


# ---------------------------------------------------------------------------
# Job code generator tests (Pattern A)
# ---------------------------------------------------------------------------
class TestJobCodeGenerator:
    def test_first_code_for_prefix(self, db):
        code = next_job_code(db, prefix="SD", year=2026)
        assert code == "26SD01"

    def test_sequential_codes(self, db):
        db.execute(
            "INSERT INTO projects (job_number, name) VALUES ('26SD01', 'First')"
        )
        db.commit()
        code = next_job_code(db, prefix="SD", year=2026)
        assert code == "26SD02"

    def test_different_prefix_resets(self, db):
        db.execute(
            "INSERT INTO projects (job_number, name) VALUES ('26SD05', 'Existing')"
        )
        db.commit()
        code = next_job_code(db, prefix="RO", year=2026)
        assert code == "26RO01"

    def test_default_year_is_current(self, db):
        from datetime import date
        yy = str(date.today().year)[-2:]
        code = next_job_code(db, prefix="SD")
        assert code.startswith(yy)


# ---------------------------------------------------------------------------
# Dry-run smoke test — full pipeline on synthetic fixture
# ---------------------------------------------------------------------------
class TestDryRunSmoke:
    def test_full_pipeline_produces_report(self, legacy_xlsx, col_map, tmp_path):
        """Run the full parse → normalize → classify pipeline on the fixture."""
        rows = parse_sheet(legacy_xlsx, sheet_name="Projects", column_map=col_map)
        assert len(rows) == 6

        normalized = [normalize_row(r, col_map) for r in rows]
        existing_jobs: set[str] = set()

        results = []
        for i, row in enumerate(normalized):
            outcome, errors = classify_row(row, i, existing_jobs)
            results.append({
                "row": i + 1,
                "job_number": row.get("job_number"),
                "name": row.get("name"),
                "outcome": outcome,
                "errors": errors,
            })

        report = build_report(results, str(legacy_xlsx), "Projects", commit=False)

        # Verify report shape
        s = report["summary"]
        assert s["mode"] == "DRY-RUN"
        assert s["total_rows"] == 6
        assert s["create"] >= 3  # at least the valid rows
        assert s["fail"] >= 1    # at least the invalid-status row

        # Verify the report can be serialized to JSON
        report_path = tmp_path / "report.json"
        with open(report_path, "w") as f:
            json.dump(report, f, default=str)
        with open(report_path) as f:
            reloaded = json.load(f)
        assert reloaded["summary"]["total_rows"] == 6
