"""Per-project _AUTO_project_summary.md renderer.

Pure function — no IO, no SharePoint, no DB connection. Callers fetch the
project + related rows and pass them in. Output is deterministic for the
same input (sorted lists, day-granular footer timestamp) so the sync layer
can short-circuit unchanged content via sha256.
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Iterable, Mapping


# Banner + footer text are part of the contract for downstream renderers,
# the verification doc, and the idempotency tests — keep them stable.
BANNER = "> ⚠️ AUTO-GENERATED. Edit in the 6DE Platform, not here."
FOOTER_TEMPLATE = (
    "_AUTO-GENERATED by 6DE Platform on {today}. "
    "Do not edit by hand — changes will be overwritten on next regeneration. "
    "Source of truth: 6DE Platform → Projects → {job}._"
)


def _fmt_money(value: float | int | None) -> str:
    if value is None:
        return "—"
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return "—"


def _fmt_date(value: str | None) -> str:
    if not value:
        return "—"
    # Accept either ISO date or datetime; render as YYYY-MM-DD.
    return str(value)[:10]


def _fmt_pct(value: float | int | None) -> str:
    if value is None:
        return "—"
    try:
        return f"{int(round(float(value)))}%"
    except (TypeError, ValueError):
        return "—"


def _fmt_text(value: str | None) -> str:
    return value.strip() if value else "—"


def _age_days(start_date: str | None, today: date | None = None) -> str:
    if not start_date:
        return "—"
    try:
        start = date.fromisoformat(str(start_date)[:10])
    except ValueError:
        return "—"
    ref = today or date.today()
    return str((ref - start).days)


def _section(title: str, body: str) -> str:
    return f"## {title}\n\n{body}\n"


def _header_block(project: Mapping, today: date | None = None) -> str:
    rows = [
        ("Job", project.get("job_number") or "—"),
        ("Name", project.get("name") or "—"),
        ("Status", project.get("status") or "—"),
        ("Priority", project.get("priority") or "—"),
        ("% Complete", _fmt_pct(project.get("percent_complete"))),
        ("Age (days)", _age_days(project.get("start_date"), today=today)),
        ("Client", _fmt_text(project.get("client_name"))),
        ("Action by", _fmt_text(project.get("action_by"))),
        ("Next action", _fmt_text(project.get("next_action"))),
    ]
    return "\n".join(f"- **{k}:** {v}" for k, v in rows)


def _dates_block(project: Mapping) -> str:
    rows = [
        ("Opened", _fmt_date(project.get("start_date"))),
        ("Target close", _fmt_date(project.get("target_end_date"))),
        ("Actual close", _fmt_date(project.get("actual_end_date"))),
    ]
    return "\n".join(f"- **{k}:** {v}" for k, v in rows)


def _financials_block(project: Mapping) -> str:
    rows = [
        ("Contract value", _fmt_money(project.get("contract_value"))),
        ("Amount paid", _fmt_money(project.get("amount_paid"))),
        ("Outstanding", _fmt_money(project.get("outstanding_balance"))),
        ("COGS", _fmt_money(project.get("cogs"))),
        ("Profit", _fmt_money(project.get("profit"))),
    ]
    return "\n".join(f"- **{k}:** {v}" for k, v in rows)


def _contacts_block(contacts: Iterable[Mapping]) -> str:
    rows = sorted(contacts, key=lambda c: (c.get("role") or "", c.get("name") or ""))
    if not rows:
        return "_No contacts on file._"
    out = ["| Name | Role | Email | Phone | Company |", "|---|---|---|---|---|"]
    for c in rows:
        out.append(
            "| {name} | {role} | {email} | {phone} | {company} |".format(
                name=_fmt_text(c.get("name")),
                role=_fmt_text(c.get("role")),
                email=_fmt_text(c.get("email")),
                phone=_fmt_text(c.get("phone")),
                company=_fmt_text(c.get("company")),
            )
        )
    return "\n".join(out)


def _updates_block(updates: Iterable[Mapping], limit: int = 10) -> str:
    rows = sorted(updates, key=lambda u: u.get("created_at") or "", reverse=True)[:limit]
    if not rows:
        return "_No updates yet._"
    out = []
    for u in rows:
        when = _fmt_date(u.get("created_at"))
        cat = u.get("category") or "note"
        body = (u.get("content") or "").strip()
        out.append(f"- **{when}** — _{cat}_ — {body}")
    return "\n".join(out)


def _notes_block(notes: Iterable[Mapping]) -> str:
    rows = sorted(notes, key=lambda n: n.get("created_at") or "", reverse=True)
    if not rows:
        return "_No notes yet._"
    out = []
    for n in rows:
        when = _fmt_date(n.get("created_at"))
        author = n.get("author") or "—"
        body = (n.get("content") or "").strip()
        out.append(f"- **{when}** (_{author}_)\n\n  {body}")
    return "\n\n".join(out)


def _documents_block(documents: Iterable[Mapping]) -> str:
    by_category: dict[str, int] = {}
    for d in documents:
        cat = d.get("category") or "Uncategorized"
        by_category[cat] = by_category.get(cat, 0) + 1
    if not by_category:
        return "_No documents indexed._"
    parts = [f"{cat}: {n}" for cat, n in sorted(by_category.items())]
    return " · ".join(parts)


def render_project_summary(
    project: Mapping,
    *,
    contacts: Iterable[Mapping] = (),
    updates: Iterable[Mapping] = (),
    notes: Iterable[Mapping] = (),
    documents: Iterable[Mapping] = (),
    today: date | None = None,
) -> str:
    """Render the per-project _AUTO_project_summary.md content.

    ``today`` is injected for deterministic tests; otherwise the renderer
    uses today's UTC date (day granularity, not minute — preserves
    idempotency across runs within a day).
    """
    today = today or datetime.now(timezone.utc).date()
    job = project.get("job_number") or "—"
    name = project.get("name") or "—"

    parts = [
        BANNER,
        "",
        f"# {job} — {name}",
        "",
        _section("Overview", _header_block(project, today=today)),
        _section("Dates", _dates_block(project)),
        _section("Financials", _financials_block(project)),
        _section("Contacts", _contacts_block(contacts)),
        _section("Recent Updates", _updates_block(updates)),
        _section("Notes", _notes_block(notes)),
        _section("Documents", _documents_block(documents)),
        FOOTER_TEMPLATE.format(today=today.isoformat(), job=job),
        "",
    ]
    # LF-only line endings — non-negotiable for idempotency on Windows hosts.
    return "\n".join(parts)
