"""Postgres backend that speaks the sqlite3 API the rest of the app uses.

Design (Phase 8 / persistent-DB cutover):
- Every module gets connections from ``db.get_connection()`` / ``db.ensure_db()``
  and writes SQLite-flavored SQL with ``?`` placeholders. Rather than porting
  ~30 modules, this adapter wraps psycopg (v3) in classes that mimic the small
  slice of the sqlite3 API the codebase actually uses, and translates the
  handful of SQLite-only constructs to Postgres at execute time.
- Errors are re-raised AS sqlite3 exceptions (IntegrityError, OperationalError,
  DatabaseError) so existing ``except sqlite3.IntegrityError`` blocks keep
  working unchanged on both backends.
- Timestamps stay TEXT ('YYYY-MM-DD HH:MM:SS') and booleans stay 0/1 integers,
  mirroring SQLite storage so every comparison/format behaves identically.
- Test isolation: each distinct db_path maps to its own Postgres schema
  (``t_<sha1(path)>``), so the existing tmp_path-based fixtures isolate tests
  on Postgres exactly like separate .db files do on SQLite. The production
  default DB_PATH maps to the ``public`` schema.

Translation rules (applied outside string literals unless noted):
- ``?``                      -> ``%s``  (and literal ``%`` doubled when params exist)
- ``datetime('now')``        -> UTC now as 'YYYY-MM-DD HH:MM:SS' text
- ``INSERT OR IGNORE``       -> ``INSERT ... ON CONFLICT DO NOTHING``
- ``LIKE``                   -> ``ILIKE`` (SQLite LIKE is case-insensitive)
- ``PRAGMA ...``             -> no-op
- ``ADD COLUMN``             -> ``ADD COLUMN IF NOT EXISTS`` (idempotent migrations)
- DDL: ``INTEGER PRIMARY KEY AUTOINCREMENT`` -> identity column, ``REAL`` ->
  ``DOUBLE PRECISION``
- ``INSERT INTO <table-with-id-pk>`` gets `` RETURNING id`` appended so
  ``cursor.lastrowid`` works.
"""
from __future__ import annotations

import hashlib
import re
import sqlite3
import threading
from datetime import date, datetime
from pathlib import Path

try:
    import psycopg
except ImportError as _e:  # pragma: no cover
    psycopg = None
    _psycopg_import_error = _e

# Captured once at import time, before any test monkeypatches config.DB_PATH.
# A connection asked for this exact path (or no path) uses the public schema;
# any other path (test tmp dirs) gets its own throwaway schema.
import config as _config

_PUBLIC_PATH = str(_config.DB_PATH)

_SQL_NOW_TEXT = "to_char((now() at time zone 'utc'), 'YYYY-MM-DD HH24:MI:SS')"

# Matches a SQL single-quoted string literal, '' escapes included.
_LITERAL_RE = re.compile(r"('(?:[^']|'')*')")
_INSERT_TABLE_RE = re.compile(r"^\s*INSERT\s+INTO\s+([A-Za-z_]\w*)", re.IGNORECASE)
_ID_TABLE_RE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z_]\w*)\s*\("
    r"[^;]*?\bid\s+INTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?\b",
    re.IGNORECASE | re.DOTALL,
)

_id_tables_cache: set[str] | None = None


def _id_tables() -> set[str]:
    """Tables whose primary key is an auto-increment ``id`` (from schema.sql)."""
    global _id_tables_cache
    if _id_tables_cache is None:
        try:
            ddl = _config.SCHEMA_PATH.read_text(encoding="utf-8")
        except OSError:
            ddl = ""
        _id_tables_cache = {m.group(1).lower() for m in _ID_TABLE_RE.finditer(ddl)}
    return _id_tables_cache


def schema_for_path(db_path: Path | str | None, default_path: Path | str) -> str:
    """Map a requested db_path to a Postgres schema name."""
    path = str(db_path) if db_path is not None else str(default_path)
    if path == _PUBLIC_PATH:
        return "public"
    digest = hashlib.sha1(path.encode("utf-8")).hexdigest()[:16]
    return f"t_{digest}"


# ---------------------------------------------------------------------------
# SQL translation
# ---------------------------------------------------------------------------
def _translate_outside_literals(segment: str, has_params: bool) -> str:
    segment = segment.replace("?", "\x00")
    if has_params:
        segment = segment.replace("%", "%%")
    segment = segment.replace("\x00", "%s")
    segment = re.sub(r"\bLIKE\b", "ILIKE", segment, flags=re.IGNORECASE)
    segment = re.sub(
        r"\bADD\s+COLUMN\s+(?!IF\s+NOT\s+EXISTS)", "ADD COLUMN IF NOT EXISTS ",
        segment, flags=re.IGNORECASE,
    )
    # DDL type/keyword mapping (harmless for DML; REAL never appears there).
    # In SQLite a bare INTEGER PRIMARY KEY is a rowid alias and auto-assigns,
    # with or without the AUTOINCREMENT keyword — map both forms to identity.
    segment = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY(\s+AUTOINCREMENT\b)?",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        segment, flags=re.IGNORECASE,
    )
    segment = re.sub(r"\bREAL\b", "DOUBLE PRECISION", segment, flags=re.IGNORECASE)
    return segment


_LEADING_COMMENTS_RE = re.compile(r"^(?:\s*(?:--[^\n]*\n?|/\*.*?\*/))*\s*", re.DOTALL)


def translate_sql(sql: str, has_params: bool) -> str:
    """Translate one SQLite-flavored statement to Postgres."""
    body = _LEADING_COMMENTS_RE.sub("", sql, count=1)
    if not body or re.match(r"^PRAGMA\b", body, flags=re.IGNORECASE):
        return ""

    if re.search(r"\bINSERT\s+OR\s+(?!IGNORE)\w+", sql, flags=re.IGNORECASE):
        raise NotImplementedError(
            "Only INSERT OR IGNORE is supported on the postgres backend; "
            f"rewrite this statement portably: {sql[:120]!r}"
        )

    # sqlite_master introspection: substitute an information_schema subquery
    # exposing the same (type, name, tbl_name, sql) columns.
    if re.search(r"\bsqlite_master\b", sql, flags=re.IGNORECASE):
        sql = re.sub(
            r"\bsqlite_master\b",
            "(SELECT 'table' AS type, table_name AS name, "
            "table_name AS tbl_name, NULL AS sql "
            "FROM information_schema.tables "
            "WHERE table_schema = current_schema() "
            "AND table_type = 'BASE TABLE' "
            "UNION ALL "
            "SELECT 'view', table_name, table_name, NULL "
            "FROM information_schema.views "
            "WHERE table_schema = current_schema()) AS sqlite_master",
            sql, flags=re.IGNORECASE,
        )

    # Fixed-token replacements that themselves contain string literals must
    # run before the literal-protection split.
    sql = re.sub(r"datetime\(\s*'now'\s*\)", _SQL_NOW_TEXT, sql, flags=re.IGNORECASE)
    sql = re.sub(
        r"CREATE\s+VIEW\s+IF\s+NOT\s+EXISTS", "CREATE OR REPLACE VIEW",
        sql, flags=re.IGNORECASE,
    )
    # Dates are TEXT 'YYYY-MM-DD'; whole-day arithmetic replaces julianday.
    sql = re.sub(
        r"julianday\(\s*'now'\s*\)\s*-\s*julianday\(([^()]+)\)",
        r"(current_date - (\1)::date)",
        sql, flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"strftime\(\s*'%Y-%m'\s*,\s*([^()]+)\)", r"substr(\1, 1, 7)",
        sql, flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"strftime\(\s*'%W'\s*,\s*([^()]+)\)", r"to_char((\1)::date, 'IW')",
        sql, flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"strftime\(\s*'%Y'\s*,\s*([^()]+)\)", r"to_char((\1)::date, 'YYYY')",
        sql, flags=re.IGNORECASE,
    )

    or_ignore = re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", sql, flags=re.IGNORECASE)
    if or_ignore:
        sql = re.sub(
            r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", sql,
            flags=re.IGNORECASE,
        )

    parts = _LITERAL_RE.split(sql)
    for i in range(0, len(parts), 2):
        parts[i] = _translate_outside_literals(parts[i], has_params)
    if has_params:
        # literal segments need % doubled too — psycopg mogrifies the whole
        # statement when parameters are present
        for i in range(1, len(parts), 2):
            parts[i] = parts[i].replace("%", "%%")
    sql = "".join(parts)

    if or_ignore:
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return sql


_translate_cache: dict[tuple[str, bool], str] = {}


def _translate_cached(sql: str, has_params: bool) -> str:
    key = (sql, has_params)
    out = _translate_cache.get(key)
    if out is None:
        out = translate_sql(sql, has_params)
        if len(_translate_cache) < 4096:
            _translate_cache[key] = out
    return out


def _coerce_param(value):
    """Mirror sqlite3's default adapters so TEXT/INTEGER columns get the
    same stored representation on both backends."""
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d %H:%M:%S")
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, Path):
        return str(value)
    item = getattr(value, "item", None)  # numpy scalars
    if item is not None and type(value).__module__.startswith("numpy"):
        return value.item()
    return value


def _coerce_params(params):
    if params is None:
        return None
    if isinstance(params, dict):
        return {k: _coerce_param(v) for k, v in params.items()}
    return tuple(_coerce_param(v) for v in params)


def _map_error(exc: Exception) -> Exception:
    """Re-raise psycopg errors as their sqlite3 equivalents so existing
    except-blocks work on both backends."""
    if psycopg is None or not isinstance(exc, psycopg.Error):
        return exc
    integrity = (
        psycopg.errors.UniqueViolation,
        psycopg.errors.CheckViolation,
        psycopg.errors.ForeignKeyViolation,
        psycopg.errors.NotNullViolation,
        psycopg.errors.ExclusionViolation,
    )
    if isinstance(exc, integrity):
        return sqlite3.IntegrityError(str(exc))
    if isinstance(exc, (psycopg.OperationalError, psycopg.ProgrammingError)):
        return sqlite3.OperationalError(str(exc))
    return sqlite3.DatabaseError(str(exc))


# ---------------------------------------------------------------------------
# sqlite3.Row work-alike
# ---------------------------------------------------------------------------
class Row:
    """Supports row[0], row['col'] (case-insensitive), keys(), iteration,
    len(), and dict(row) - the sqlite3.Row surface the app uses."""

    __slots__ = ("_cols", "_index", "_values")

    def __init__(self, cols, index, values):
        self._cols = cols
        self._index = index
        self._values = values

    def __getitem__(self, key):
        if isinstance(key, str):
            try:
                return self._values[self._index[key.lower()]]
            except KeyError:
                raise IndexError(f"no such column: {key}") from None
        return self._values[key]

    def keys(self):
        return list(self._cols)

    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)

    def __contains__(self, value):
        return value in self._values

    def __repr__(self):  # pragma: no cover
        return f"Row({dict(zip(self._cols, self._values))!r})"


# ---------------------------------------------------------------------------
# Cursor / Connection adapters
# ---------------------------------------------------------------------------
_PRAGMA_TABLE_INFO_RE = re.compile(
    r"^\s*PRAGMA\s+table_info\(\s*['\"]?(\w+)['\"]?\s*\)", re.IGNORECASE
)
_PRAGMA_DATABASE_LIST_RE = re.compile(
    r"^\s*PRAGMA\s+database_list\b", re.IGNORECASE
)


class PgCursor:
    def __init__(self, conn: "PgConnection"):
        self._conn = conn
        self._cur = conn._pg.cursor()
        self.lastrowid: int | None = None
        self._synthetic: list[Row] | None = None
        self._row_meta: tuple | None = None

    # -- sqlite PRAGMA emulation ---------------------------------------------
    def _emulate_pragma(self, sql: str) -> bool:
        """Handle the PRAGMA forms the app/tests actually read. Returns True
        if the statement was handled (other PRAGMAs become no-ops)."""
        m = _PRAGMA_TABLE_INFO_RE.match(sql)
        if m:
            # Same column order as sqlite: (cid, name, type, notnull,
            # dflt_value, pk). pk is reported as 0 — no current caller uses it
            # on the postgres backend (_expand_project_status_check is
            # sqlite-only).
            self.execute(
                "SELECT ordinal_position - 1 AS cid, column_name AS name, "
                "       data_type AS type, "
                "       CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull, "
                "       column_default AS dflt_value, 0 AS pk "
                "FROM information_schema.columns "
                "WHERE table_schema = current_schema() AND table_name = ? "
                "ORDER BY ordinal_position",
                (m.group(1).lower(),),
            )
            return True
        if _PRAGMA_DATABASE_LIST_RE.match(sql):
            cols = ["seq", "name", "file"]
            index = {c: i for i, c in enumerate(cols)}
            self._synthetic = [Row(cols, index, (0, "main", self._conn.db_path))]
            return True
        return False

    # -- DBAPI surface ------------------------------------------------------
    def execute(self, sql: str, params=None):
        self._synthetic = None
        self._row_meta = None
        if re.match(r"^\s*PRAGMA\b", sql, flags=re.IGNORECASE) and \
                self._emulate_pragma(sql):
            return self
        has_params = params is not None and len(params) > 0
        translated = _translate_cached(sql, has_params)
        if not translated:  # remaining PRAGMAs etc.
            return self

        inject_returning = False
        m = _INSERT_TABLE_RE.match(translated)
        if m and m.group(1).lower() in _id_tables() and \
                "returning" not in translated.lower():
            translated += " RETURNING id"
            inject_returning = True

        coerced = _coerce_params(params) if has_params else None
        with self._conn._lock:
            try:
                self._cur.execute(translated, coerced)
                self._conn._track_changes(self._cur.rowcount, translated)
                if inject_returning:
                    rows = self._cur.fetchall()
                    self.lastrowid = rows[-1][0] if rows else None
            except Exception as exc:  # noqa: BLE001
                raise _map_error(exc) from exc
        return self

    def executemany(self, sql: str, seq_of_params):
        seq = [(_coerce_params(p) or ()) for p in seq_of_params]
        translated = _translate_cached(sql, True)
        with self._conn._lock:
            try:
                self._cur.executemany(translated, seq)
                self._conn._track_changes(self._cur.rowcount, translated)
            except Exception as exc:  # noqa: BLE001
                raise _map_error(exc) from exc
        return self

    def _wrap_rows(self, raw_rows):
        # cols/index are derived once per result set (reset in execute), not
        # per fetch call — fetchone() in a loop would otherwise rebuild them
        # for every row.
        if self._row_meta is None:
            desc = self._cur.description
            cols = [d.name for d in desc] if desc else []
            index = {c.lower(): i for i, c in enumerate(cols)}
            self._row_meta = (cols, index)
        cols, index = self._row_meta
        return [Row(cols, index, r) for r in raw_rows]

    def fetchone(self):
        if self._synthetic is not None:
            return self._synthetic.pop(0) if self._synthetic else None
        with self._conn._lock:
            raw = self._cur.fetchone()
        if raw is None:
            return None
        return self._wrap_rows([raw])[0]

    def fetchall(self):
        if self._synthetic is not None:
            rows, self._synthetic = self._synthetic, []
            return rows
        with self._conn._lock:
            raw = self._cur.fetchall()
        return self._wrap_rows(raw)

    def fetchmany(self, size=None):
        if self._synthetic is not None:
            n = size or 1
            rows, self._synthetic = self._synthetic[:n], self._synthetic[n:]
            return rows
        with self._conn._lock:
            raw = self._cur.fetchmany(size) if size else self._cur.fetchmany()
        return self._wrap_rows(raw)

    @property
    def rowcount(self):
        return self._cur.rowcount

    @property
    def description(self):
        return self._cur.description

    def close(self):
        self._cur.close()

    def __iter__(self):
        return iter(self.fetchall())


class PgConnection:
    """Mimics the sqlite3.Connection surface used by the app: execute(),
    executemany(), executescript(), cursor(), commit(), rollback(), close(),
    total_changes, row_factory attribute, and context-manager protocol."""

    def __init__(self, conninfo: str, schema: str, db_path: str = ""):
        self.db_path = db_path  # original requested path (PRAGMA database_list)
        if psycopg is None:  # pragma: no cover
            raise sqlite3.OperationalError(
                "DB_BACKEND=postgres requires the 'psycopg[binary]' package: "
                f"{_psycopg_import_error}"
            )
        self._lock = threading.RLock()
        self._total_changes = 0
        self.row_factory = None  # accepted, ignored (rows are always Row)
        try:
            self._pg = psycopg.connect(conninfo, autocommit=True)
        except Exception as exc:  # noqa: BLE001
            # Never re-raise connect errors verbatim: libpq DSN-parse errors
            # can echo the conninfo string, which embeds the password.
            host = getattr(getattr(exc, "diag", None), "message_primary", None)
            raise sqlite3.OperationalError(
                "could not connect to the configured Postgres server "
                f"(schema {schema!r}): {type(exc).__name__}"
                + (f": {host}" if host and conninfo not in str(host) else "")
            ) from None
        try:
            if schema != "public":
                self._pg.execute(
                    f'CREATE SCHEMA IF NOT EXISTS "{schema}"'
                )
            self._pg.execute(f'SET search_path TO "{schema}"')
            # SQLite's ROUND(x, n) accepts floats; Postgres only has
            # round(numeric, int). Install a per-schema shim so the app's
            # widespread ROUND(<float expr>, n) keeps working unchanged.
            self._pg.execute(
                f'CREATE OR REPLACE FUNCTION "{schema}".round('
                "double precision, integer) RETURNS numeric AS "
                "'SELECT round($1::numeric, $2)' LANGUAGE SQL IMMUTABLE"
            )
        except Exception as exc:  # noqa: BLE001
            raise _map_error(exc) from exc
        self.schema = schema

    # -- internals ----------------------------------------------------------
    def _track_changes(self, rowcount: int, sql: str) -> None:
        if rowcount and rowcount > 0 and re.match(
            r"\s*(INSERT|UPDATE|DELETE)\b", sql, flags=re.IGNORECASE
        ):
            self._total_changes += rowcount

    # -- sqlite3.Connection surface ------------------------------------------
    def execute(self, sql: str, params=None) -> PgCursor:
        return PgCursor(self).execute(sql, params)

    def executemany(self, sql: str, seq_of_params) -> PgCursor:
        return PgCursor(self).executemany(sql, seq_of_params)

    def executescript(self, script: str) -> None:
        """Run a multi-statement script (schema DDL). No parameters."""
        statements = _split_script(script)
        with self._lock:
            try:
                for stmt in statements:
                    translated = _translate_cached(stmt, False)
                    if translated.strip():
                        self._pg.execute(translated)
            except Exception as exc:  # noqa: BLE001
                raise _map_error(exc) from exc

    def cursor(self) -> PgCursor:
        return PgCursor(self)

    @property
    def total_changes(self) -> int:
        return self._total_changes

    def commit(self) -> None:
        # autocommit mode: an explicit BEGIN opens a server-side transaction;
        # commit only if one is actually open (mirrors sqlite autocommit).
        with self._lock:
            if self._pg.info.transaction_status != \
                    psycopg.pq.TransactionStatus.IDLE:
                self._pg.execute("COMMIT")

    def rollback(self) -> None:
        with self._lock:
            if self._pg.info.transaction_status != \
                    psycopg.pq.TransactionStatus.IDLE:
                self._pg.execute("ROLLBACK")

    def close(self) -> None:
        try:
            self._pg.close()
        except Exception:  # noqa: BLE001
            pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        return False


def _split_script(script: str) -> list[str]:
    """Split schema DDL on top-level semicolons (no procedural bodies in our
    schema; string literals are respected)."""
    statements: list[str] = []
    parts = _LITERAL_RE.split(script)
    buf: list[str] = []
    for i, part in enumerate(parts):
        if i % 2 == 1:  # string literal: never split inside
            buf.append(part)
            continue
        while ";" in part:
            head, part = part.split(";", 1)
            buf.append(head)
            statements.append("".join(buf))
            buf = []
        buf.append(part)
    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return [s for s in statements if s.strip()]


def connect(database_url: str, db_path, default_path) -> PgConnection:
    schema = schema_for_path(db_path, default_path)
    return PgConnection(
        database_url, schema, str(db_path if db_path is not None else default_path)
    )
